app/timesheet/sheets/urls.py
"""Defines URL patterns for sheets."""
from django.urls import path
from . import views

app_name = 'timesheets'
urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    #path('timesheets/', views.timesheet, name='timesheet'),
    path('new_timesheet/', views.newtimesheet, name='newtimesheet'),
    path('view_timesheet/', views.view_timesheet, name='view_timesheet'),
    ]

app/timesheet/timesheet/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sheets.urls')),
    path('users/', include('users.urls'))
]

app/timesheet/users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
    # Include default auth urls.
    path('', include('django.contrib.auth.urls')),
    # Registration page.
    path('register/', views.register, name='register'),
    ]

app/timesheet/sheets/models.py
from django.db import models

# Create your models here.
from django.db import models


# Create your models here.
class Project(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        """Returns string representation of project name."""
        return self.name


class Activity(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        verbose_name_plural = 'activities'

    def __str__(self):
        """Returns string representation of activity"""
        return self.name


class Client(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        """Returns string representation of a client"""
        return self.name


class User(models.Model):
    username = models.CharField(max_length=255)
    password = models.CharField(max_length=30)
    mail = models.EmailField(max_length=100)

    def __str__(self):
        """Returns string representation of a user"""
        return self.username


class Timesheet(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    activity = models.ForeignKey(Activity, on_delete=models.CASCADE)
    monday = models.PositiveSmallIntegerField()
    tuesday = models.PositiveSmallIntegerField()
    wednesday = models.PositiveSmallIntegerField()
    thursday = models.PositiveSmallIntegerField()
    friday = models.PositiveSmallIntegerField()
    saturday = models.PositiveSmallIntegerField()
    sunday = models.PositiveSmallIntegerField()

app/timesheet/users/models.py
from django.db import models

# Create your models here.

app/timesheet/sheets/forms.py
from django import forms

from .models import Timesheet


class TimesheetForm(forms.ModelForm):
    class Meta:
        model = Timesheet
        fields = ['user', 'client', 'project', 'activity', 'monday', 'tuesday', 'wednesday', 'thursday',
                  'friday', 'saturday', 'sunday']

app/timesheet/sheets/views.py
from django.shortcuts import render, redirect
from .models import Timesheet, Project, Client, Activity
from .forms import TimesheetForm


# Create your views here.
def index(request):
    """The home page for time sheets."""
    return render(request, 'timesheets/index.html')


# def timesheet(request):
#     """Default Time sheet table"""
#     time_sheet = Timesheet.objects.all()
#     clients = Client.objects.all()
#     projects = Project.objects.all()
#     activities = Activity. objects.all()
#     context = {'time_sheet': time_sheet,
#                'clients': clients,
#                'projects': projects,
#                'activities': activities}
#     return render(request, 'timesheets/timesheet.html', context)


def newtimesheet(request):
    """Adds new time sheet to the database"""
    if request.method != 'POST':
        form = TimesheetForm()
    else:
        # POST data submitted; process data.
        form = TimesheetForm(data=request.POST)
        if form.is_valid():
            new_timesheet = form.save(commit=False)
            new_timesheet.save()
            return redirect('timesheets:view_timesheet')

        # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'timesheets/new_timesheet.html', context)


def view_timesheet(request):
    """Views all time sheets from the database. """
    ts_view = Timesheet.objects.all()
    context = {'ts_view': ts_view}
    return render(request, 'timesheets/view_timesheet.html', context)

app/timesheet/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm


# Create your views here.
def register(request):
    """Register a new user."""
    if request.method != 'POST':
        # Display blank registration form.
        form = UserCreationForm()
    else:
        # Process completed form.
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # Log the user in and then redirect to home page.
            login(request, new_user)
            return redirect('sheets:index')

    # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'registration/register.html', context)

app/timesheet/sheets/templates/sheets/base.html
<p>
    <!--    <a href="{% url 'timesheets:index' %}">Time Sheets</a> - -->
        <a href="{% url 'sheets:view_timesheet' %}">Timesheet</a> -
        {% if user.is_authenticated %}
          Hello, {{ user.username }}.
          <a href="{% url 'users:logout' %}">Log out</a>
        {% else %}
          <a href="{% url 'users:register' %}">Register</a> -
          <a href="{% url 'users:login' %}">Log in</a>
        {% endif %}
    </p>
    
    {% block content %}{% endblock content %}
    

app/timesheet/sheets/templates/sheets/index.html
{% extends "sheets/base.html" %}

{% block content %}
    <h1>Timesheet</h1>
    <p>Timesheet helps you keep track of your projects, clients, activities and working hours.</p>
{% endblock content %}

app/timesheet/sheets/templates/sheets/new_timesheet.html
{% extends "sheets/base.html" %}

{% block content %}

    <p>New timesheet</p>
    <form action="{% url 'sheets:newtimesheet' %}" method='post'>
      {% csrf_token %}
      {{ form.as_p }}
      <button name="submit">Add timesheet</button>
    </form>

{% endblock content %}

app/timesheet/sheets/templates/sheets/timesheet.html
{% extends "sheets/base.html" %}

{% block content %}
    <style>
    thead {color: green;}
    th, td {
    padding: 5px;
    border: 1px solid black;
    }
    </style>
    <a href="{% url 'sheets:newtimesheet' %}">Add new time sheet</a>
    <table>
        <thead>
           <th>User</th> <th>Client</th> <th>Project</th> <th>Activity</th> <th>Week</th> <th>Monday</th> <th>Tuesday</th> <th>Wednesday</th>
            <th>Thursday</th> <th>Friday</th> <th>Saturday</th> <th>Sunday</th>
        </thead>
        {% for timesheet in time_sheet %}
        <tr>
            <td>{{ timesheet.user }}</td>
            <td>
                <select>
                    {% for client in clients %}
                        <option>{{ client }}</option>
                    {% endfor %}
                </select>
            </td>
            <td>
                <select>
                    {% for project in projects %}
                        <option>{{ project }}</option>
                    {% endfor %}
                </select>
            </td>
            <td>
                <select>
                    {% for activity in activities %}
                        <option>{{ activity }}</option>
                    {% endfor %}
                </select>
            </td>
            <td>
                <input type="week">
            </td>
            <td>
                <input name="monday" type="number" min="0" max="10">
            </td>
            <td>
                <input type="number" min="0" max="10">
            </td>
            <td>
                <input type="number" min="0" max="10">
            </td>
            <td>
                <input type="number" min="0" max="10">
            </td>
            <td>
                <input type="number" min="0" max="10">
            </td>
            <td>
                <input type="number" min="0" max="10">
            </td>
            <td>
                <input type="number" min="0" max="10">
            </td>
        </tr>
        {% endfor %}
    </table>

{% endblock content %}

app/timesheet/sheets/templates/sheets/view_timesheet.html
{% extends "sheets/base.html" %}

{% block content %}
    <style>
    thead {color: green;}
    th, td {
    padding: 5px;
    border: 1px solid black;
    }
    </style>
    <a href="{% url 'sheets:newtimesheet' %}">Add new time sheet</a>
    <table>
        <thead>
           <th>User</th> <th>Client</th> <th>Project</th> <th>Activity</th> <th>Week</th> <th>Monday</th> <th>Tuesday</th> <th>Wednesday</th>
            <th>Thursday</th> <th>Friday</th> <th>Saturday</th> <th>Sunday</th>
        </thead>
        {% for category in ts_view %}
        <tr>
            <td>{{ category.user }}</td>
            <td>{{ category.client }}</td>
            <td>{{ category.project }}</td>
            <td>{{ category.activity }}</td>
            <td>
                <input type="week">
            </td>
            <td>{{ category.monday }}</td>
            <td>{{ category.tuesday }}</td>
            <td>{{ category.wednesday }}</td>
            <td>{{ category.thursday }}</td>
            <td>{{ category.friday }}</td>
            <td>{{ category.saturday }}</td>
            <td>{{ category.sunday }}</td>
        </tr>
        {% endfor %}
    </table>

{% endblock content %}